language: node_js
node_js:
  - '8'
cache:
  directories:
    - node_modules
notifications:
  webhooks:
    urls:
      - https://discordapp.com/api/webhooks/478101125627772928/NNvtwoCOhS-7KugzsBRwg52M2m62zhfCPUi9WZxvEB6SXUORm-O4oK5G6XQFQrTAQy4q
    on_success: always # default: always
    on_failure: always # default: always
    on_start: never   # default: never
    on_cancel: always # default: always
    on_error: always # default: always
